### ISSUE TITLE
Analisar se op (operation) é um token no JavaCC

### ISSUE THREAD

**Issue by leolinhares** [UFC-CC-2016-Projects/Team-4#3]
@mivl

**Comment by mivl** [comment]
O JavaCC não aceita o token "&&" como parte da expresão regular de OP.

**Comment by leolinhares** [comment]
Teoricamente o token op deveria ser definido com <OP: <STAR>|<AND>|<LT>|<PLUS>|<MINUS>>, porém aparece um erro de compilação informando que AND nunca poderá ser classificado como OP. Não sei porque isso acontece, mas é necessário que OP seja um token.

**Comment by leolinhares** [comment]
Op acabou sendo redefinido dentro das expressões, então o token `<OP>` não existirá mais. 327a3e2 resolveu essa issue.
